### ISSUE TITLE
Base OS Image configuration and auto build

### ISSUE THREAD

**Issue by mhl787156** [StarlingUAS/ProjectStarling#30]
Configuration and auto build system for base OS images

**Comment by rob-clarke** [comment]
k3s configuration in: `/etc/rancher/k3s/config.yaml`

Content:
```yaml
node-label:
  - "starling.uas/type=vehicle"
node-taint:
  - "starling.uas/type=vehicle:NoSchedule"
```
